#!/usr/bin/env python3
import os
import sys
import subprocess
from pathlib import Path

def run_command(cmd, cwd=None):
    try:
        result = subprocess.run(cmd, shell=True, cwd=cwd, capture_output=True, text=True)
        if result.returncode != 0:
            print(f"❌ Erreur: {result.stderr}")
            return False
        return True
    except Exception as e:
        print(f"❌ Exception: {e}")
        return False

def create_file(filepath, content):
    filepath = Path(filepath)
    filepath.parent.mkdir(parents=True, exist_ok=True)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"✅ {filepath}")

def main():
    print("\n" + "="*60)
    print("SETUP PLANTRIPAVE - COMPLET")
    print("="*60 + "\n")

    print("📁 Creation Backend...\n")

    create_file('backend/controllers/tripController.js', 
        "const Trip = require('../models/Trip');\n"
        "const Place = require('../models/Place');\n"
        "const Budget = require('../models/Budget');\n"
        "const { calculateOptimalRoute } = require('../utils/routeOptimizer');\n\n"
        "exports.createTrip = async (req, res) => {\n"
        "  try {\n"
        "    const { name, startDate, endDate, budget, userId } = req.body;\n"
        "    if (!name || !startDate || !endDate || !userId) {\n"
        "      return res.status(400).json({ error: 'Champs obligatoires manquants' });\n"
        "    }\n"
        "    const trip = await Trip.create({\n"
        "      name, startDate, endDate, budget, userId, status: 'planning'\n"
        "    });\n"
        "    res.status(201).json(trip);\n"
        "  } catch (error) {\n"
        "    res.status(500).json({ error: error.message });\n"
        "  }\n"
        "};\n\n"
        "exports.getUserTrips = async (req, res) => {\n"
        "  try {\n"
        "    const { userId } = req.params;\n"
        "    const trips = await Trip.findAll({\n"
        "      where: { userId },\n"
        "      include: [\n"
        "        { model: Place, as: 'places' },\n"
        "        { model: Budget, as: 'budgets' }\n"
        "      ],\n"
        "      order: [['startDate', 'DESC']]\n"
        "    });\n"
        "    res.json(trips);\n"
        "  } catch (error) {\n"
        "    res.status(500).json({ error: error.message });\n"
        "  }\n"
        "};\n\n"
        "exports.getTripById = async (req, res) => {\n"
        "  try {\n"
        "    const { tripId } = req.params;\n"
        "    const trip = await Trip.findByPk(tripId, {\n"
        "      include: [\n"
        "        { model: Place, as: 'places' },\n"
        "        { model: Budget, as: 'budgets' }\n"
        "      ]\n"
        "    });\n"
        "    if (!trip) {\n"
        "      return res.status(404).json({ error: 'Trip non trouvé' });\n"
        "    }\n"
        "    res.json(trip);\n"
        "  } catch (error) {\n"
        "    res.status(500).json({ error: error.message });\n"
        "  }\n"
        "};\n\n"
        "exports.updateTrip = async (req, res) => {\n"
        "  try {\n"
        "    const { tripId } = req.params;\n"
        "    const { name, startDate, endDate, budget, status } = req.body;\n"
        "    const trip = await Trip.findByPk(tripId);\n"
        "    if (!trip) {\n"
        "      return res.status(404).json({ error: 'Trip non trouvé' });\n"
        "    }\n"
        "    await trip.update({\n"
        "      name: name || trip.name,\n"
        "      startDate: startDate || trip.startDate,\n"
        "      endDate: endDate || trip.endDate,\n"
        "      budget: budget || trip.budget,\n"
        "      status: status || trip.status\n"
        "    });\n"
        "    res.json(trip);\n"
        "  } catch (error) {\n"
        "    res.status(500).json({ error: error.message });\n"
        "  }\n"
        "};\n\n"
        "exports.deleteTrip = async (req, res) => {\n"
        "  try {\n"
        "    const { tripId } = req.params;\n"
        "    const trip = await Trip.findByPk(tripId);\n"
        "    if (!trip) {\n"
        "      return res.status(404).json({ error: 'Trip non trouvé' });\n"
        "    }\n"
        "    await trip.destroy();\n"
        "    res.json({ message: 'Trip supprimé avec succès' });\n"
        "  } catch (error) {\n"
        "    res.status(500).json({ error: error.message });\n"
        "  }\n"
        "};\n"
    )

    create_file('backend/controllers/placeController.js',
        "const Place = require('../models/Place');\n"
        "const Trip = require('../models/Trip');\n\n"
        "exports.addPlace = async (req, res) => {\n"
        "  try {\n"
        "    const { tripId } = req.params;\n"
        "    const { name, latitude, longitude, description, visitDate, estimatedCost } = req.body;\n"
        "    if (!name || latitude === undefined || longitude === undefined) {\n"
        "      return res.status(400).json({ error: 'Champs obligatoires manquants' });\n"
        "    }\n"
        "    const trip = await Trip.findByPk(tripId);\n"
        "    if (!trip) {\n"
        "      return res.status(404).json({ error: 'Trip non trouvé' });\n"
        "    }\n"
        "    const place = await Place.create({\n"
        "      tripId, name, latitude, longitude, description, visitDate,\n"
        "      estimatedCost: estimatedCost || 0, order: 0\n"
        "    });\n"
        "    res.status(201).json(place);\n"
        "  } catch (error) {\n"
        "    res.status(500).json({ error: error.message });\n"
        "  }\n"
        "};\n\n"
        "exports.getTripPlaces = async (req, res) => {\n"
        "  try {\n"
        "    const { tripId } = req.params;\n"
        "    const places = await Place.findAll({\n"
        "      where: { tripId },\n"
        "      order: [['order', 'ASC']]\n"
        "    });\n"
        "    res.json(places);\n"
        "  } catch (error) {\n"
        "    res.status(500).json({ error: error.message });\n"
        "  }\n"
        "};\n\n"
        "exports.updatePlace = async (req, res) => {\n"
        "  try {\n"
        "    const { placeId } = req.params;\n"
        "    const { name, latitude, longitude, description, visitDate, estimatedCost, order } = req.body;\n"
        "    const place = await Place.findByPk(placeId);\n"
        "    if (!place) {\n"
        "      return res.status(404).json({ error: 'Lieu non trouvé' });\n"
        "    }\n"
        "    await place.update({\n"
        "      name: name || place.name,\n"
        "      latitude: latitude !== undefined ? latitude : place.latitude,\n"
        "      longitude: longitude !== undefined ? longitude : place.longitude,\n"
        "      description: description || place.description,\n"
        "      visitDate: visitDate || place.visitDate,\n"
        "      estimatedCost: estimatedCost !== undefined ? estimatedCost : place.estimatedCost,\n"
        "      order: order !== undefined ? order : place.order\n"
        "    });\n"
        "    res.json(place);\n"
        "  } catch (error) {\n"
        "    res.status(500).json({ error: error.message });\n"
        "  }\n"
        "};\n\n"
        "exports.deletePlace = async (req, res) => {\n"
        "  try {\n"
        "    const { placeId } = req.params;\n"
        "    const place = await Place.findByPk(placeId);\n"
        "    if (!place) {\n"
        "      return res.status(404).json({ error: 'Lieu non trouvé' });\n"
        "    }\n"
        "    await place.destroy();\n"
        "    res.json({ message: 'Lieu supprimé avec succès' });\n"
        "  } catch (error) {\n"
        "    res.status(500).json({ error: error.message });\n"
        "  }\n"
        "};\n\n"
        "exports.reorderPlaces = async (req, res) => {\n"
        "  try {\n"
        "    const { tripId } = req.params;\n"
        "    const { places } = req.body;\n"
        "    for (const place of places) {\n"
        "      await Place.update(\n"
        "        { order: place.order },\n"
        "        { where: { id: place.id, tripId } }\n"
        "      );\n"
        "    }\n"
        "    const updatedPlaces = await Place.findAll({\n"
        "      where: { tripId },\n"
        "      order: [['order', 'ASC']]\n"
        "    });\n"
        "    res.json(updatedPlaces);\n"
        "  } catch (error) {\n"
        "    res.status(500).json({ error: error.message });\n"
        "  }\n"
        "};\n"
    )

    create_file('backend/controllers/budgetController.js',
        "const Budget = require('../models/Budget');\n"
        "const Trip = require('../models/Trip');\n\n"
        "exports.addExpense = async (req, res) => {\n"
        "  try {\n"
        "    const { tripId } = req.params;\n"
        "    const { category, amount, description, date } = req.body;\n"
        "    if (!category || amount === undefined) {\n"
        "      return res.status(400).json({ error: 'Champs obligatoires manquants' });\n"
        "    }\n"
        "    const trip = await Trip.findByPk(tripId);\n"
        "    if (!trip) {\n"
        "      return res.status(404).json({ error: 'Trip non trouvé' });\n"
        "    }\n"
        "    const budget = await Budget.create({\n"
        "      tripId, category, amount, description,\n"
        "      date: date || new Date()\n"
        "    });\n"
        "    res.status(201).json(budget);\n"
        "  } catch (error) {\n"
        "    res.status(500).json({ error: error.message });\n"
        "  }\n"
        "};\n\n"
        "exports.getTripExpenses = async (req, res) => {\n"
        "  try {\n"
        "    const { tripId } = req.params;\n"
        "    const expenses = await Budget.findAll({\n"
        "      where: { tripId },\n"
        "      order: [['date', 'DESC']]\n"
        "    });\n"
        "    const totalExpenses = expenses.reduce((sum, exp) => sum + exp.amount, 0);\n"
        "    res.json({\n"
        "      expenses,\n"
        "      totalExpenses,\n"
        "      remainingBudget: (await Trip.findByPk(tripId)).budget - totalExpenses\n"
        "    });\n"
        "  } catch (error) {\n"
        "    res.status(500).json({ error: error.message });\n"
        "  }\n"
        "};\n\n"
        "exports.updateExpense = async (req, res) => {\n"
        "  try {\n"
        "    const { expenseId } = req.params;\n"
        "    const { category, amount, description, date } = req.body;\n"
        "    const expense = await Budget.findByPk(expenseId);\n"
        "    if (!expense) {\n"
        "      return res.status(404).json({ error: 'Dépense non trouvée' });\n"
        "    }\n"
        "    await expense.update({\n"
        "      category: category || expense.category,\n"
        "      amount: amount !== undefined ? amount : expense.amount,\n"
        "      description: description || expense.description,\n"
        "      date: date || expense.date\n"
        "    });\n"
        "    res.json(expense);\n"
        "  } catch (error) {\n"
        "    res.status(500).json({ error: error.message });\n"
        "  }\n"
        "};\n\n"
        "exports.deleteExpense = async (req, res) => {\n"
        "  try {\n"
        "    const { expenseId } = req.params;\n"
        "    const expense = await Budget.findByPk(expenseId);\n"
        "    if (!expense) {\n"
        "      return res.status(404).json({ error: 'Dépense non trouvée' });\n"
        "    }\n"
        "    await expense.destroy();\n"
        "    res.json({ message: 'Dépense supprimée avec succès' });\n"
        "  } catch (error) {\n"
        "    res.status(500).json({ error: error.message });\n"
        "  }\n"
        "};\n\n"
        "exports.getBudgetSummary = async (req, res) => {\n"
        "  try {\n"
        "    const { tripId } = req.params;\n"
        "    const trip = await Trip.findByPk(tripId);\n"
        "    if (!trip) {\n"
        "      return res.status(404).json({ error: 'Trip non trouvé' });\n"
        "    }\n"
        "    const expenses = await Budget.findAll({ where: { tripId } });\n"
        "    const summary = {\n"
        "      totalBudget: trip.budget,\n"
        "      totalSpent: expenses.reduce((sum, exp) => sum + exp.amount, 0),\n"
        "      remaining: trip.budget - expenses.reduce((sum, exp) => sum + exp.amount, 0),\n"
        "      byCategory: {}\n"
        "    };\n"
        "    expenses.forEach(exp => {\n"
        "      if (!summary.byCategory[exp.category]) {\n"
        "        summary.byCategory[exp.category] = 0;\n"
        "      }\n"
        "      summary.byCategory[exp.category] += exp.amount;\n"
        "    });\n"
        "    res.json(summary);\n"
        "  } catch (error) {\n"
        "    res.status(500).json({ error: error.message });\n"
        "  }\n"
        "};\n"
    )

    create_file('backend/models/User.js',
        "const { DataTypes } = require('sequelize');\n"
        "const sequelize = require('../config/database');\n"
        "const bcrypt = require('bcryptjs');\n\n"
        "const User = sequelize.define('User', {\n"
        "  email: { type: DataTypes.STRING, unique: true, allowNull: false },\n"
        "  password: { type: DataTypes.STRING, allowNull: false },\n"
        "  name: DataTypes.STRING\n"
        "}, {\n"
        "  hooks: {\n"
        "    beforeCreate: async (user) => {\n"
        "      user.password = await bcrypt.hash(user.password, 10);\n"
        "    }\n"
        "  }\n"
        "});\n\n"
        "module.exports = User;\n"
    )

    create_file('backend/models/Trip.js',
        "const { DataTypes } = require('sequelize');\n"
        "const sequelize = require('../config/database');\n\n"
        "const Trip = sequelize.define('Trip', {\n"
        "  name: { type: DataTypes.STRING, allowNull: false },\n"
        "  startDate: DataTypes.DATE,\n"
        "  endDate: DataTypes.DATE,\n"
        "  budget: DataTypes.FLOAT,\n"
        "  status: { type: DataTypes.STRING, defaultValue: 'planning' }\n"
        "});\n\n"
        "module.exports = Trip;\n"
    )

    create_file('backend/models/Place.js',
        "const { DataTypes } = require('sequelize');\n"
        "const sequelize = require('../config/database');\n\n"
        "const Place = sequelize.define('Place', {\n"
        "  name: { type: DataTypes.STRING, allowNull: false },\n"
        "  latitude: { type: DataTypes.FLOAT, allowNull: false },\n"
        "  longitude: { type: DataTypes.FLOAT, allowNull: false },\n"
        "  description: DataTypes.TEXT,\n"
        "  visitDate: DataTypes.DATE,\n"
        "  estimatedCost: { type: DataTypes.FLOAT, defaultValue: 0 },\n"
        "  order: { type: DataTypes.INTEGER, defaultValue: 0 }\n"
        "});\n\n"
        "module.exports = Place;\n"
    )

    create_file('backend/models/Budget.js',
        "const { DataTypes } = require('sequelize');\n"
        "const sequelize = require('../config/database');\n\n"
        "const Budget = sequelize.define('Budget', {\n"
        "  category: { type: DataTypes.STRING, allowNull: false },\n"
        "  amount: { type: DataTypes.FLOAT, allowNull: false },\n"
        "  description: DataTypes.TEXT,\n"
        "  date: { type: DataTypes.DATE, defaultValue: DataTypes.NOW }\n"
        "});\n\n"
        "module.exports = Budget;\n"
    )

    create_file('backend/routes/trips.js',
        "const express = require('express');\n"
        "const router = express.Router();\n"
        "const tripController = require('../controllers/tripController');\n"
        "const placeController = require('../controllers/placeController');\n"
        "const budgetController = require('../controllers/budgetController');\n"
        "const auth = require('../middleware/auth');\n\n"
        "router.post('/', auth, tripController.createTrip);\n"
        "router.get('/user/:userId', auth, tripController.getUserTrips);\n"
        "router.get('/:tripId', auth, tripController.getTripById);\n"
        "router.put('/:tripId', auth, tripController.updateTrip);\n"
        "router.delete('/:tripId', auth, tripController.deleteTrip);\n\n"
        "router.post('/:tripId/places', auth, placeController.addPlace);\n"
        "router.get('/:tripId/places', auth, placeController.getTripPlaces);\n"
        "router.put('/places/:placeId', auth, placeController.updatePlace);\n"
        "router.delete('/places/:placeId', auth, placeController.deletePlace);\n"
        "router.put('/:tripId/places/reorder', auth, placeController.reorderPlaces);\n\n"
        "router.post('/:tripId/expenses', auth, budgetController.addExpense);\n"
        "router.get('/:tripId/expenses', auth, budgetController.getTripExpenses);\n"
        "router.put('/expenses/:expenseId', auth, budgetController.updateExpense);\n"
        "router.delete('/expenses/:expenseId', auth, budgetController.deleteExpense);\n"
        "router.get('/:tripId/budget-summary', auth, budgetController.getBudgetSummary);\n\n"
        "module.exports = router;\n"
    )

    create_file('backend/middleware/auth.js',
        "const jwt = require('jsonwebtoken');\n\n"
        "module.exports = (req, res, next) => {\n"
        "  const token = req.headers.authorization?.split(' ')[1];\n"
        "  if (!token) {\n"
        "    return res.status(401).json({ error: 'Token manquant' });\n"
        "  }\n"
        "  try {\n"
        "    const decoded = jwt.verify(token, process.env.JWT_SECRET);\n"
        "    req.userId = decoded.id;\n"
        "    next();\n"
        "  } catch (error) {\n"
        "    return res.status(401).json({ error: 'Token invalide' });\n"
        "  }\n"
        "};\n"
    )

    create_file('backend/config/database.js',
        "const { Sequelize } = require('sequelize');\n\n"
        "const sequelize = new Sequelize(\n"
        "  process.env.DB_NAME,\n"
        "  process.env.DB_USER,\n"
        "  process.env.DB_PASSWORD,\n"
        "  {\n"
        "    host: process.env.DB_HOST,\n"
        "    dialect: 'postgres',\n"
        "    port: 5432\n"
        "  }\n"
        ");\n\n"
        "module.exports = sequelize;\n"
    )

    create_file('backend/utils/routeOptimizer.js',
        "function calculateDistance(lat1, lon1, lat2, lon2) {\n"
        "  const R = 6371;\n"
        "  const dLat = (lat2 - lat1) * (Math.PI / 180);\n"
        "  const dLon = (lon2 - lon1) * (Math.PI / 180);\n"
        "  const a = Math.sin(dLat / 2) * Math.sin(dLat / 2) + Math.cos(lat1 * (Math.PI / 180)) * Math.cos(lat2 * (Math.PI / 180)) * Math.sin(dLon / 2) * Math.sin(dLon / 2);\n"
        "  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));\n"
        "  return R * c;\n"
        "}\n\n"
        "function nearestNeighbor(places) {\n"
        "  if (places.length === 0) return [];\n"
        "  if (places.length === 1) return places;\n"
        "  const unvisited = [...places];\n"
        "  const route = [unvisited.shift()];\n"
        "  while (unvisited.length > 0) {\n"
        "    const current = route[route.length - 1];\n"
        "    let nearest = unvisited[0];\n"
        "    let minDistance = calculateDistance(current.latitude, current.longitude, nearest.latitude, nearest.longitude);\n"
        "    for (let i = 1; i < unvisited.length; i++) {\n"
        "      const distance = calculateDistance(current.latitude, current.longitude, unvisited[i].latitude, unvisited[i].longitude);\n"
        "      if (distance < minDistance) {\n"
        "        minDistance = distance;\n"
        "        nearest = unvisited[i];\n"
        "      }\n"
        "    }\n"
        "    route.push(nearest);\n"
        "    unvisited.splice(unvisited.indexOf(nearest), 1);\n"
        "  }\n"
        "  return route;\n"
        "}\n\n"
        "async function calculateOptimalRoute(places) {\n"
        "  if (!places || places.length === 0) {\n"
        "    return { route: [], totalDistance: 0, optimizationLevel: 'N/A' };\n"
        "  }\n"
        "  const optimized = nearestNeighbor(places);\n"
        "  let totalDistance = 0;\n"
        "  for (let i = 0; i < optimized.length - 1; i++) {\n"
        "    totalDistance += calculateDistance(\n"
        "      optimized[i].latitude,\n"
        "      optimized[i].longitude,\n"
        "      optimized[i + 1].latitude,\n"
        "      optimized[i + 1].longitude\n"
        "    );\n"
        "  }\n"
        "  return {\n"
        "    route: optimized,\n"
        "    totalDistance: Math.round(totalDistance * 100) / 100,\n"
        "    optimizationLevel: 'Nearest Neighbor'\n"
        "  };\n"
        "}\n\n"
        "module.exports = { calculateOptimalRoute, calculateDistance };\n"
    )

    create_file('backend/package.json',
        "{\n"
        "  \"name\": \"plantripave-backend\",\n"
        "  \"version\": \"0.1.0\",\n"
        "  \"main\": \"server.js\",\n"
        "  \"scripts\": {\n"
        "    \"dev\": \"nodemon server.js\",\n"
        "    \"start\": \"node server.js\"\n"
        "  },\n"
        "  \"dependencies\": {\n"
        "    \"express\": \"^4.18.2\",\n"
        "    \"sequelize\": \"^6.35.2\",\n"
        "    \"pg\": \"^8.11.3\",\n"
        "    \"bcryptjs\": \"^2.4.3\",\n"
        "    \"jsonwebtoken\": \"^9.1.2\",\n"
        "    \"dotenv\": \"^16.3.1\",\n"
        "    \"cors\": \"^2.8.5\"\n"
        "  },\n"
        "  \"devDependencies\": {\n"
        "    \"nodemon\": \"^3.0.2\"\n"
        "  }\n"
        "}\n"
    )

    create_file('backend/server.js',
        "const express = require('express');\n"
        "const cors = require('cors');\n"
        "const dotenv = require('dotenv');\n"
        "const sequelize = require('./config/database');\n"
        "const tripRoutes = require('./routes/trips');\n\n"
        "dotenv.config();\n\n"
        "const app = express();\n"
        "app.use(cors());\n"
        "app.use(express.json());\n\n"
        "const User = require('./models/User');\n"
        "const Trip = require('./models/Trip');\n"
        "const Place = require('./models/Place');\n"
        "const Budget = require('./models/Budget');\n\n"
        "Trip.hasMany(Place, { as: 'places', foreignKey: 'tripId' });\n"
        "Place.belongsTo(Trip, { foreignKey: 'tripId' });\n"
        "Trip.hasMany(Budget, { as: 'budgets', foreignKey: 'tripId' });\n"
        "Budget.belongsTo(Trip, { foreignKey: 'tripId' });\n"
        "User.hasMany(Trip, { foreignKey: 'userId' });\n"
        "Trip.belongsTo(User, { foreignKey: 'userId' });\n\n"
        "app.use('/api/trips', tripRoutes);\n\n"
        "app.listen(process.env.PORT || 5000, () => {\n"
        "  console.log('Server running on port ' + (process.env.PORT || 5000));\n"
        "  sequelize.sync().then(() => {\n"
        "    console.log('Database connected');\n"
        "  }).catch(err => console.error('DB Error:', err));\n"
        "});\n"
    )

    create_file('backend/.env',
        "PORT=5000\n"
        "DB_HOST=localhost\n"
        "DB_USER=postgres\n"
        "DB_PASSWORD=yourpassword\n"
        "DB_NAME=plantripave\n"
        "JWT_SECRET=your_secret_key_here\n"
        "NODE_ENV=development\n"
    )

    print("\n📁 Creation Frontend...\n")

    create_file('frontend/src/pages/Dashboard.jsx',
        "import React, { useState, useEffect } from 'react';\n"
        "import axios from 'axios';\n"
        "import '../styles/Dashboard.css';\n\n"
        "function Dashboard() {\n"
        "  const [trips, setTrips] = useState([]);\n"
        "  const [newTrip, setNewTrip] = useState({ name: '', startDate: '', endDate: '', budget: '' });\n"
        "  const [loading, setLoading] = useState(true);\n"
        "  const userId = localStorage.getItem('userId');\n"
        "  const token = localStorage.getItem('token');\n\n"
        "  useEffect(() => {\n"
        "    fetchTrips();\n"
        "  }, []);\n\n"
        "  const fetchTrips = async () => {\n"
        "    try {\n"
        "      const response = await axios.get(\n"
        "        `${process.env.REACT_APP_API_URL}/trips/user/${userId}`,\n"
        "        { headers: { Authorization: `Bearer ${token}` } }\n"
        "      );\n"
        "      setTrips(response.data);\n"
        "    } catch (error) {\n"
        "      console.error('Erreur:', error);\n"
        "    } finally {\n"
        "      setLoading(false);\n"
        "    }\n"
        "  };\n\n"
        "  const handleCreateTrip = async (e) => {\n"
        "    e.preventDefault();\n"
        "    try {\n"
        "      const response = await axios.post(\n"
        "        `${process.env.REACT_APP_API_URL}/trips`,\n"
        "        { ...newTrip, budget: parseFloat(newTrip.budget), userId },\n"
        "        { headers: { Authorization: `Bearer ${token}` } }\n"
        "      );\n"
        "      setTrips([...trips, response.data]);\n"
        "      setNewTrip({ name: '', startDate: '', endDate: '', budget: '' });\n"
        "    } catch (error) {\n"
        "      console.error('Erreur:', error);\n"
        "    }\n"
        "  };\n\n"
        "  const handleDeleteTrip = async (tripId) => {\n"
        "    try {\n"
        "      await axios.delete(\n"
        "        `${process.env.REACT_APP_API_URL}/trips/${tripId}`,\n"
        "        { headers: { Authorization: `Bearer ${token}` } }\n"
        "      );\n"
        "      setTrips(trips.filter(t => t.id !== tripId));\n"
        "    } catch (error) {\n"
        "      console.error('Erreur:', error);\n"
        "    }\n"
        "  };\n\n"
        "  if (loading) return <div>Chargement...</div>;\n\n"
        "  return (\n"
        "    <div className=\"dashboard-container\">\n"
        "      <h1>Mes Voyages</h1>\n"
        "      <div className=\"form-section\">\n"
        "        <h2>Creer un nouveau voyage</h2>\n"
        "        <form onSubmit={handleCreateTrip}>\n"
        "          <input type=\"text\" placeholder=\"Nom du voyage\" value={newTrip.name} onChange={(e) => setNewTrip({ ...newTrip, name: e.target.value })} required />\n"
        "          <input type=\"date\" value={newTrip.startDate} onChange={(e) => setNewTrip({ ...newTrip, startDate: e.target.value })} required />\n"
        "          <input type=\"date\" value={newTrip.endDate} onChange={(e) => setNewTrip({ ...newTrip, endDate: e.target.value })} required />\n"
        "          <input type=\"number\" step=\"0.01\" placeholder=\"Budget (EUR)\" value={newTrip.budget} onChange={(e) => setNewTrip({ ...newTrip, budget: e.target.value })} required />\n"
        "          <button type=\"submit\">Creer</button>\n"
        "        </form>\n"
        "      </div>\n"
        "      <div className=\"trips-grid\">\n"
        "        {trips.length === 0 ? <p>Aucun voyage</p> : trips.map((trip) => (\n"
        "          <div key={trip.id} className=\"trip-card\">\n"
        "            <h3>{trip.name}</h3>\n"
        "            <p>{new Date(trip.startDate).toLocaleDateString()}</p>\n"
        "            <p>Budget: {trip.budget} EUR</p>\n"
        "            <div className=\"card-actions\">\n"
        "              <a href={`/trip/${trip.id}`} className=\"btn-primary\">Details</a>\n"
        "              <button onClick={() => handleDeleteTrip(trip.id)} className=\"btn-danger\">Supprimer</button>\n"
        "            </div>\n"
        "          </div>\n"
        "        ))}\n"
        "      </div>\n"
        "    </div>\n"
        "  );\n"
        "}\n\n"
        "export default Dashboard;\n"
    )

    create_file('frontend/src/pages/TripPlanner.jsx',
        "import React, { useState, useEffect } from 'react';\n"
        "import axios from 'axios';\n"
        "import '../styles/TripPlanner.css';\n\n"
        "function TripPlanner() {\n"
        "  const tripId = window.location.pathname.split('/')[2];\n"
        "  const [trip, setTrip] = useState(null);\n"
        "  const [places, setPlaces] = useState([]);\n"
        "  const [newPlace, setNewPlace] = useState({ name: '', latitude: '', longitude: '' });\n"
        "  const [loading, setLoading] = useState(true);\n"
        "  const token = localStorage.getItem('token');\n\n"
        "  useEffect(() => {\n"
        "    fetchTripData();\n"
        "  }, [tripId]);\n\n"
        "  const fetchTripData = async () => {\n"
        "    try {\n"
        "      const tripRes = await axios.get(\n"
        "        `${process.env.REACT_APP_API_URL}/trips/${tripId}`,\n"
        "        { headers: { Authorization: `Bearer ${token}` } }\n"
        "      );\n"
        "      setTrip(tripRes.data);\n"
        "      const placesRes = await axios.get(\n"
        "        `${process.env.REACT_APP_API_URL}/trips/${tripId}/places`,\n"
        "        { headers: { Authorization: `Bearer ${token}` } }\n"
        "      );\n"
        "      setPlaces(placesRes.data);\n"
        "    } catch (error) {\n"
        "      console.error('Erreur:', error);\n"
        "    } finally {\n"
        "      setLoading(false);\n"
        "    }\n"
        "  };\n\n"
        "  const handleAddPlace = async (e) => {\n"
        "    e.preventDefault();\n"
        "    try {\n"
        "      const response = await axios.post(\n"
        "        `${process.env.REACT_APP_API_URL}/trips/${tripId}/places`,\n"
        "        { ...newPlace, latitude: parseFloat(newPlace.latitude), longitude: parseFloat(newPlace.longitude) },\n"
        "        { headers: { Authorization: `Bearer ${token}` } }\n"
        "      );\n"
        "      setPlaces([...places, response.data]);\n"
        "      setNewPlace({ name: '', latitude: '', longitude: '' });\n"
        "    } catch (error) {\n"
        "      console.error('Erreur:', error);\n"
        "    }\n"
        "  };\n\n"
        "  const handleDeletePlace = async (placeId) => {\n"
        "    try {\n"
        "      await axios.delete(\n"
        "        `${process.env.REACT_APP_API_URL}/trips/places/${placeId}`,\n"
        "        { headers: { Authorization: `Bearer ${token}` } }\n"
        "      );\n"
        "      setPlaces(places.filter(p => p.id !== placeId));\n"
        "    } catch (error) {\n"
        "      console.error('Erreur:', error);\n"
        "    }\n"
        "  };\n\n"
        "  if (loading) return <div>Chargement...</div>;\n"
        "  if (!trip) return <div>Trip non trouve</div>;\n\n"
        "  return (\n"
        "    <div className=\"planner-container\">\n"
        "      <h1>{trip.name}</h1>\n"
        "      <div className=\"planner-grid\">\n"
        "        <div className=\"info-section\">\n"
        "          <h2>Ajouter un lieu</h2>\n"
        "          <form onSubmit={handleAddPlace}>\n"
        "            <input type=\"text\" placeholder=\"Nom du lieu\" value={newPlace.name} onChange={(e) => setNewPlace({ ...newPlace, name: e.target.value })} required />\n"
        "            <input type=\"number\" step=\"0.0001\" placeholder=\"Latitude\" value={newPlace.latitude} onChange={(e) => setNewPlace({ ...newPlace, latitude: e.target.value })} required />\n"
        "            <input type=\"number\" step=\"0.0001\" placeholder=\"Longitude\" value={newPlace.longitude} onChange={(e) => setNewPlace({ ...newPlace, longitude: e.target.value })} required />\n"
        "            <button type=\"submit\">Ajouter</button>\n"
        "          </form>\n"
        "          <h3>Lieux ({places.length})</h3>\n"
        "          <ul className=\"places-list\">\n"
        "            {places.map((place) => (\n"
        "              <li key={place.id}>\n"
        "                <div><strong>{place.name}</strong><p>{place.latitude}, {place.longitude}</p></div>\n"
        "                <button onClick={() => handleDeletePlace(place.id)} className=\"btn-delete\">X</button>\n"
        "              </li>\n"
        "            ))}\n"
        "          </ul>\n"
        "        </div>\n"
        "      </div>\n"
        "    </div>\n"
        "  );\n"
        "}\n\n"
        "export default TripPlanner;\n"
    )

    create_file('frontend/src/pages/BudgetTracker.jsx',
        "import React, { useState, useEffect } from 'react';\n"
        "import axios from 'axios';\n"
        "import '../styles/BudgetTracker.css';\n\n"
        "function BudgetTracker() {\n"
        "  const tripId = window.location.pathname.split('/')[2];\n"
        "  const [trip, setTrip] = useState(null);\n"
        "  const [expenses, setExpenses] = useState([]);\n"
        "  const [newExpense, setNewExpense] = useState({ category: 'Transport', amount: '', description: '' });\n"
        "  const [loading, setLoading] = useState(true);\n"
        "  const token = localStorage.getItem('token');\n\n"
        "  useEffect(() => {\n"
        "    fetchData();\n"
        "  }, [tripId]);\n\n"
        "  const fetchData = async () => {\n"
        "    try {\n"
        "      const tripRes = await axios.get(\n"
        "        `${process.env.REACT_APP_API_URL}/trips/${tripId}`,\n"
        "        { headers: { Authorization: `Bearer ${token}` } }\n"
        "      );\n"
        "      setTrip(tripRes.data);\n"
        "      const expensesRes = await axios.get(\n"
        "        `${process.env.REACT_APP_API_URL}/trips/${tripId}/expenses`,\n"
        "        { headers: { Authorization: `Bearer ${token}` } }\n"
        "      );\n"
        "      setExpenses(expensesRes.data.expenses);\n"
        "    } catch (error) {\n"
        "      console.error('Erreur:', error);\n"
        "    } finally {\n"
        "      setLoading(false);\n"
        "    }\n"
        "  };\n\n"
        "  const handleAddExpense = async (e) => {\n"
        "    e.preventDefault();\n"
        "    try {\n"
        "      const response = await axios.post(\n"
        "        `${process.env.REACT_APP_API_URL}/trips/${tripId}/expenses`,\n"
        "        { ...newExpense, amount: parseFloat(newExpense.amount) },\n"
        "        { headers: { Authorization: `Bearer ${token}` } }\n"
        "      );\n"
        "      setExpenses([...expenses, response.data]);\n"
        "      setNewExpense({ category: 'Transport', amount: '', description: '' });\n"
        "    } catch (error) {\n"
        "      console.error('Erreur:', error);\n"
        "    }\n"
        "  };\n\n"
        "  const handleDeleteExpense = async (expenseId) => {\n"
        "    try {\n"
        "      await axios.delete(\n"
        "        `${process.env.REACT_APP_API_URL}/trips/expenses/${expenseId}`,\n"
        "        { headers: { Authorization: `Bearer ${token}` } }\n"
        "      );\n"
        "      setExpenses(expenses.filter(e => e.id !== expenseId));\n"
        "    } catch (error) {\n"
        "      console.error('Erreur:', error);\n"
        "    }\n"
        "  };\n\n"
        "  if (loading) return <div>Chargement...</div>;\n\n"
        "  return (\n"
        "    <div className=\"budget-container\">\n"
        "      <h1>Budget</h1>\n"
        "      <div className=\"budget-grid\">\n"
        "        <div className=\"expenses-section\">\n"
        "          <h2>Ajouter une depense</h2>\n"
        "          <form onSubmit={handleAddExpense}>\n"
        "            <select value={newExpense.category} onChange={(e) => setNewExpense({ ...newExpense, category: e.target.value })}>\n"
        "              <option>Transport</option><option>Hebergement</option><option>Nourriture</option><option>Activites</option>\n"
        "            </select>\n"
        "            <input type=\"number\" step=\"0.01\" placeholder=\"Montant (EUR)\" value={newExpense.amount} onChange={(e) => setNewExpense({ ...newExpense, amount: e.target.value })} required />\n"
        "            <input type=\"text\" placeholder=\"Description\" value={newExpense.description} onChange={(e) => setNewExpense({ ...newExpense, description: e.target.value })} />\n"
        "            <button type=\"submit\">Ajouter</button>\n"
        "          </form>\n"
        "        </div>\n"
        "        <div className=\"expenses-list-section\">\n"
        "          <h2>Depenses</h2>\n"
        "          <ul className=\"expenses-list\">\n"
        "            {expenses.map((expense) => (\n"
        "              <li key={expense.id} className=\"expense-item\">\n"
        "                <div><strong>{expense.category}</strong><p>{expense.description}</p></div>\n"
        "                <div className=\"expense-actions\">\n"
        "                  <span className=\"amount\">{expense.amount} EUR</span>\n"
        "                  <button onClick={() => handleDeleteExpense(expense.id)} className=\"btn-delete\">X</button>\n"
        "                </div>\n"
        "              </li>\n"
        "            ))}\n"
        "          </ul>\n"
        "        </div>\n"
        "      </div>\n"
        "    </div>\n"
        "  );\n"
        "}\n\n"
        "export default BudgetTracker;\n"
    )

    create_file('frontend/src/styles/Dashboard.css',
        ".dashboard-container { max-width: 1200px; margin: 0 auto; padding: 20px; }\n"
        ".dashboard-container h1 { color: #333; margin-bottom: 30px; }\n"
        ".form-section { background: white; padding: 25px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1); margin-bottom: 40px; }\n"
        ".form-section form { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; }\n"
        ".form-section input { padding: 12px; border: 1px solid #ddd; border-radius: 4px; }\n"
        ".form-section button { padding: 12px 25px; background: #007bff; color: white; border: none; border-radius: 4px; cursor: pointer; }\n"
        ".form-section button:hover { background: #0056b3; }\n"
        ".trips-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 20px; }\n"
        ".trip-card { background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1); }\n"
        ".trip-card h3 { color: #333; margin-bottom: 10px; }\n"
        ".trip-card p { color: #666; margin: 5px 0; }\n"
        ".card-actions { display: flex; gap: 10px; margin-top: 15px; }\n"
        ".btn-primary, .btn-danger { flex: 1; padding: 10px; border: none; border-radius: 4px; cursor: pointer; text-decoration: none; text-align: center; }\n"
        ".btn-primary { background: #28a745; color: white; }\n"
        ".btn-danger { background: #dc3545; color: white; }\n"
    )

    create_file('frontend/src/styles/TripPlanner.css',
        ".planner-container { max-width: 1200px; margin: 0 auto; padding: 20px; }\n"
        ".planner-container h1 { color: #333; margin-bottom: 20px; }\n"
        ".planner-grid { display: grid; grid-template-columns: 1fr; gap: 20px; }\n"
        ".info-section { background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1); }\n"
        ".info-section h2 { color: #555; margin-bottom: 15px; }\n"
        ".info-section form { display: flex; flex-direction: column; gap: 10px; margin-bottom: 20px; }\n"
        ".info-section input { padding: 10px; border: 1px solid #ddd; border-radius: 4px; }\n"
        ".info-section button { padding: 10px; background: #007bff; color: white; border: none; border-radius: 4px; cursor: pointer; }\n"
        ".places-list { list-style: none; padding: 0; }\n"
        ".places-list li { display: flex; justify-content: space-between; align-items: center; padding: 12px; border-bottom: 1px solid #eee; gap: 10px; }\n"
        ".btn-delete { background: #dc3545; color: white; border: none; border-radius: 50%; width: 30px; height: 30px; cursor: pointer; }\n"
    )

    create_file('frontend/src/styles/BudgetTracker.css',
        ".budget-container { max-width: 1200px; margin: 0 auto; padding: 20px; }\n"
        ".budget-container h1 { color: #333; margin-bottom: 30px; }\n"
        ".budget-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }\n"
        ".expenses-section, .expenses-list-section { background: white; padding: 25px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1); }\n"
        ".expenses-section h2, .expenses-list-section h2 { color: #555; margin-bottom: 20px; }\n"
        ".expenses-section form { display: flex; flex-direction: column; gap: 12px; }\n"
        ".expenses-section select, .expenses-section input { padding: 12px; border: 1px solid #ddd; border-radius: 4px; }\n"
        ".expenses-section button { padding: 12px; background: #28a745; color: white; border: none; border-radius: 4px; cursor: pointer; }\n"
        ".expenses-list { list-style: none; padding: 0; }\n"
        ".expense-item { display: flex; justify-content: space-between; align-items: center; padding: 15px; border-bottom: 1px solid #eee; gap: 15px; }\n"
        ".expense-item strong { color: #333; display: block; margin-bottom: 5px; }\n"
        ".expense-item p { color: #666; margin: 0; }\n"
        ".expense-actions { display: flex; align-items: center; gap: 15px; }\n"
        ".expense-actions .amount { font-weight: bold; color: #dc3545; }\n"
    )

    create_file('frontend/src/App.jsx',
        "import React from 'react';\n"
        "import { BrowserRouter as Router, Routes, Route, Navigate } from 'react-router-dom';\n"
        "import Dashboard from './pages/Dashboard';\n"
        "import TripPlanner from './pages/TripPlanner';\n"
        "import BudgetTracker from './pages/BudgetTracker';\n"
        "import './App.css';\n\n"
        "function App() {\n"
        "  const token = localStorage.getItem('token');\n"
        "  return (\n"
        "    <Router>\n"
        "      <Routes>\n"
        "        <Route path=\"/dashboard\" element={token ? <Dashboard /> : <Navigate to=\"/login\" />} />\n"
        "        <Route path=\"/trip/:tripId\" element={token ? <TripPlanner /> : <Navigate to=\"/login\" />} />\n"
        "        <Route path=\"/trip/:tripId/budget\" element={token ? <BudgetTracker /> : <Navigate to=\"/login\" />} />\n"
        "        <Route path=\"/\" element={<Navigate to={token ? \"/dashboard\" : \"/login\"} />} />\n"
        "      </Routes>\n"
        "    </Router>\n"
        "  );\n"
        "}\n\n"
        "export default App;\n"
    )

    create_file('frontend/src/App.css',
        "* { margin: 0; padding: 0; box-sizing: border-box; }\n"
        "body { font-family: Arial, sans-serif; background-color: #f5f5f5; }\n"
    )

    create_file('frontend/src/index.js',
        "import React from 'react';\n"
        "import ReactDOM from 'react-dom/client';\n"
        "import App from './App';\n\n"
        "const root = ReactDOM.createRoot(document.getElementById('root'));\n"
        "root.render(\n"
        "  <React.StrictMode>\n"
        "    <App />\n"
        "  </React.StrictMode>\n"
        ");\n"
    )

    create_file('frontend/package.json',
        "{\n"
        "  \"name\": \"plantripave-frontend\",\n"
        "  \"version\": \"0.1.0\",\n"
        "  \"private\": true,\n"
        "  \"dependencies\": {\n"
        "    \"react\": \"^18.2.0\",\n"
        "    \"react-dom\": \"^18.2.0\",\n"
        "    \"react-router-dom\": \"^6.20.0\",\n"
        "    \"axios\": \"^1.6.2\"\n"
        "  },\n"
        "  \"scripts\": {\n"
        "    \"start\": \"react-scripts start\",\n"
        "    \"build\": \"react-scripts build\"\n"
        "  },\n"
        "  \"devDependencies\": {\n"
        "    \"react-scripts\": \"5.0.1\"\n"
        "  }\n"
        "}\n"
    )

    create_file('frontend/.env',
        "REACT_APP_API_URL=http://localhost:5000/api\n"
    )

    create_file('frontend/public/index.html',
        "<!DOCTYPE html>\n"
        "<html lang=\"fr\">\n"
        "  <head>\n"
        "    <meta charset=\"utf-8\" />\n"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
        "    <title>PlanTripSave</title>\n"
        "  </head>\n"
        "  <body>\n"
        "    <div id=\"root\"></div>\n"
        "  </body>\n"
        "</html>\n"
    )

    create_file('README.md',
        "# PlanTripSave\n\n"
        "Application de planification et gestion de voyages avec optimisation d'itineraires.\n\n"
        "## Features\n\n"
        "- Creer et gerer vos voyages\n"
        "- Planifier vos destinations\n"
        "- Suivre vos depenses par categorie\n"
        "- Optimiser vos itineraires\n\n"
        "## Installation\n\n"
        "### Backend\n"
        "```bash\n"
        "cd backend\n"
        "npm install\n"
        "npm run dev\n"
        "```\n\n"
        "### Frontend\n"
        "```bash\n"
        "cd frontend\n"
        "npm install\n"
        "npm start\n"
        "```\n\n"
        "## Configuration\n\n"
        "Creer un fichier `.env` dans `backend/` avec:\n"
        "```\n"
        "PORT=5000\n"
        "DB_HOST=localhost\n"
        "DB_USER=postgres\n"
        "DB_PASSWORD=yourpassword\n"
        "DB_NAME=plantripave\n"
        "JWT_SECRET=your_secret_key\n"
        "NODE_ENV=development\n"
        "```\n\n"
        "## API Endpoints\n\n"
        "### Trips\n"
        "- POST /api/trips - Creer un voyage\n"
        "- GET /api/trips/user/:userId - Recuperer les voyages\n"
        "- GET /api/trips/:tripId - Details d'un voyage\n"
        "- PUT /api/trips/:tripId - Mettre a jour\n"
        "- DELETE /api/trips/:tripId - Supprimer\n\n"
        "### Places\n"
        "- POST /api/trips/:tripId/places - Ajouter un lieu\n"
        "- GET /api/trips/:tripId/places - Recuperer les lieux\n"
        "- DELETE /api/trips/places/:placeId - Supprimer un lieu\n\n"
        "### Expenses\n"
        "- POST /api/trips/:tripId/expenses - Ajouter une depense\n"
        "- GET /api/trips/:tripId/expenses - Recuperer les depenses\n"
        "- DELETE /api/trips/expenses/:expenseId - Supprimer une depense\n\n"
        "## License\n\n"
        "MIT\n"
    )

    create_file('.gitignore',
        "node_modules/\n"
        "*.env\n"
        ".env.local\n"
        ".env.*.local\n"
        "dist/\n"
        "build/\n"
        ".DS_Store\n"
        "*.swp\n"
        ".vscode/\n"
        ".idea/\n"
    )

    print("\n" + "="*60)
    print("✅ TOUS LES FICHIERS CREES!")
    print("="*60 + "\n")

    token = input("🔑 Entre ton GitHub Token: ").strip()

    if not token:
        print("❌ Token manquant!")
        sys.exit(1)

    print("\n🔄 Configuration Git et push...\n")

    os.chdir(os.path.dirname(os.path.abspath(__file__)))

    run_command('git init')
    run_command('git config user.email "bot@github.com"')
    run_command('git config user.name "Setup Bot"')
    run_command('git add .')
    run_command('git commit -m "🚀 Initial PlanTripSave setup"')
    run_command('git branch -M main')
    run_command('git remote add origin https://github.com/YOUR_USERNAME/PlanTripSave.git')
    run_command('git push -u origin main')

    print("\n" + "="*60)
    print("✅ SETUP COMPLETE!")
    print("✅ Fichiers crees avec succes!")
    print("✅ Repository pousse sur GitHub!")
    print("="*60 + "\n")
    print("📝 Prochaines etapes:")
    print("   1. cd backend && npm install")
    print("   2. cd ../frontend && npm install")
    print("   3. npm run dev (backend) et npm start (frontend)")
    print("\n")

if __name__ == "__main__":
    main()